APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/PrimaryPillDosingCycleChipButton.swift, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
+ 메인 약 추가 뷰 레이아웃 구현
+ 메인 약 이름 / 약 용량 UITextField 구현
+ 메인 약 DosingCycle 아침 / 점심 / 저녁 버튼
+ 버튼 초기화 클래스 파일 생성
=> [Feat] #13 - 메인 약 추가 뷰 Layout 구현

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents, APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/CoreData/History+CoreDataClass.swift, APillLog/APillLog/CoreData/History+CoreDataProperties.swift, APillLog/APillLog/View/Base.lproj/Main.storyboard, APillLog/APillLog/View/DiaryTab/DiaryView.storyboard, APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
함수정리 노션에 있습니다.
많이 부족합니다. 리뷰 부탁드려요
=> [Feat] CoreData 함수 추가

APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.xib, APillLog/APillLog/View/HistoryTab/HistoryView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
- Coredata 연결
- TabView가 변경될 때 table 데이터 업데이트하도록 구현
- 현재 Button을 누르면 history가 업데이트됨.
|Prototype|HistoryView|
|---|---|
|<img src = "https://user-images.githubusercontent.com/68676844/179931599-2ff71b23-eff6-4e6e-827f-232162559464.png" width=250> |<img src = "https://user-images.githubusercontent.com/68676844/179931536-c6083261-4cbf-47f8-b25b-82fe14152187.png" width = 250>|
=> [Feat] #39 - HistoryView에 Coredata 연결

APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
=> [Feat] 메인약 추가페이지에서 텍스트필드 강조 기능 추가

APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
+ 증상 입력 시 반환 값이 문자열이 아닌 문자열 배열로 반환
=> [Feat] #65 - 증상 입력 시 반환 값이 문자열이 아닌 배열로 반환

APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift
- 메인약 이름과 용량이 똑같을 때는 추가할 수 없도록 저장 버튼 비활성화 + 경고메시지 보여주기
=> [Feat] #67 - 메인약 중복되는 입력 방지 기능 추가

APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryView.storyboard, APillLog/APillLog/View/DiaryTab/DiaryViewController.swift
- 리스트에서 실수노트 삭제기능 추가
- 사용자가 실수노트를 수정하고 다른 페이지로 이동시에 자동으로 저장되는 기능 추가
- 코어데이터 CBT(실수노트) 관련 함수 추가
https://user-images.githubusercontent.com/72395020/180400745-cd913a1a-50c4-44d7-af5f-bb997ad29c57.mp4
=> [Feat] #26 #22 - DiaryView 수정

APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents, APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
- AddSecondaryPillView에서 최근에 선택한 서브약 상위에 보여주기 기능 추가
https://user-images.githubusercontent.com/39216546/180402720-9cdc10df-049a-4832-9185-700dd3c8dd4a.mp4
=> [Feat] #70 - 서브약 추천 기능 구현

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents, APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/CoreData/History+CoreDataClass.swift, APillLog/APillLog/CoreData/History+CoreDataProperties.swift, APillLog/APillLog/View/HistoryTab/HistoryViewController.swift, APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.swift, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
1. ShowPrimaryPill 중복 방지함수
2. 토글 시 ShowPrimaryPill 삭제가능하게수정
3. ShowPrimaryPill 삭제하면 Histroy도 같이 삭제 함수 추가
=> [Fix] 함수오류수정

APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
패딩 값 오차는 다음 커밋 때 보완하겠습니다
datasource의 count가 0일 때 "복용할 약이 없어요"문구가 나오지 않는데 이 부분도 수정하겠습니다
=> [Fix] #59 Dynamic Height TableView

APillLog/APillLog/CoreData/APillLog.xcdatamodeld/APillLog.xcdatamodel/contents, APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
테이블 cell의 삽입, 삭제의 경우 reloadData를 사용하지 못한다.
insert의 경우
IndexPath(row: primaryPillList.count-1, section: 0)
- beginUpdates()
- insertRows(at: indexPath, with: .automatic)
- endUpdates()
를 사용한다
=> [Fix] PrimaryPill 추가 시 발생하는 오류해결

APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard, APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
- divider 길이 늘리기
- textfield가 비어있을 때 약 추가하기 버튼 비활성화 (색, 기능)
=> [Feat] #87 - AddSecondaryPillView 레이아웃 수정

APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionView.storyboard, APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift
+ 선택된 칩의 글자를 bold로 설정
+ 추가 기록 부분 최대 글자수 제한 및 출력
=> [Feat] #85 CheckConditionView 기능/디자인 수정

APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard
- AddPrimaryPill placeholder 수정 "mg,정 단위로 입력해주세요"
=> [Style] #86 - AddPrimaryPill placeholder 수정

APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/Extentions/APillLog+Font.swift, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.swift, APillLog/APillLog/View/MedicationTab/CustomCell/MedicationPillCell.xib, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
#83 이슈를 확인해주세요
- #81 이슈를 위한 @mycookie1 의 코드를 추가해서 PR합니다
- 이어서 #94 이슈 작업하겠습니다
=> [Fix] #76, #81, #83 메인뷰 UI 수정 및 코어데이터 코드 추가

APillLog/APillLog/View/MedicationTab/MedicationView.storyboard, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
출시를 위해 
기능구현이 아직 안된 부분을 임시 삭제합니다
=> [Fix] #94 - Medication view/taking all pills button 임시 삭제

APillLog/APillLog/View/HistoryTab/HistoryView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
=> [Feat] Calendar View 비어있을 때 수정

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/Application/AppDelegate.swift, APillLog/APillLog/Info.plist, APillLog/APillLog/View/Base.lproj/Main.storyboard, APillLog/APillLog/View/DiaryTab/DiaryView.storyboard
다이어리뷰의 가이드 텍스트 크기를 수정하였습니다.
탭바의 색상을 변경하였습니다.
=> [Fix] 다이어리뷰 텍스트 크기 변경, 탭바 수정

APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift
- 약물 용량의 키보드를 숫자 키보드로 변경
- mg / 정과 같은 단위 설정을 위한 segmented control 추가
=> [Feat] #113 - AddPrimaryPillView 피드백 반영

APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift, APillLog/APillLog/View/HistoryTab/HistoryViewController.swift, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/CheckCondition/CheckConditionViewController.swift, APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
=> [Refactor] #131 - CoreDataManager 싱글톤 변환

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.swift, APillLog/APillLog/View/HistoryTab/HistoryTableViewCell.xib, APillLog/APillLog/View/HistoryTab/HistoryView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryViewController.swift
- 시간에 오전/오후 추가
- 개선사항 관련 코드 제거
- 복약기록과 증상기록 구분을 위해 이모지 추가
=> [Fix] - #90 히스토리뷰 UI개선

APillLog/APillLog/View/Base.lproj/LaunchScreen.storyboard, APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationController.swift
https://user-images.githubusercontent.com/68676844/181939404-7a8868b7-32df-4590-bf46-1a115821d0de.mp4
=> [Fix] 저녁 시간 저장 안 되는 문제 해결

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/Extentions/APillLog+Font.swift, APillLog/APillLog/View/FSCalendarView/FSCalendarView.storyboard, APillLog/APillLog/View/FSCalendarView/FSCalendarViewController.swift, APillLog/APillLog/View/HistoryTab/HistoryView.storyboard
<p align="center"><img width=300 height=600 src="https://user-images.githubusercontent.com/86882798/182012196-7e1f21dc-80b2-4409-a5c0-868c785e355e.png"></p>
- FSCalendar Layout
- Month 이동 버튼
- 선택 날짜/금일 날짜 색상 변경
=> [Feat] FSCalendar 구현

APillLog/APillLog/CoreData/CoreDataManager.swift
- 일주일 전 데이터를 통해 먹은 약, 안 먹은 약 모두 가지고 옴
- 복용 버튼 누른 후 알림 끌 때 복용한 약이 아닌 경우에만 삭제하도록 변경
- #161 
- #162 
https://user-images.githubusercontent.com/68676844/182020954-c12a222a-5c85-4fe5-bbc9-542ad26fe478.mp4
=> [Feat] 복용률 보이는 방법 수정 

APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingView.storyboard
- [워딩] 복용관리 -> 약 등록으로 변경
- [디자인] 일반 리스트 -> 카드 형식으로 변경
|변경 후 화면|이전 화면|
|---|---|
=> [Feat] 복용 관리 페이지 디자인 수정

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/CustomLicenseTableCell.swift, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseController.swift, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/ChartsLicenseView.storyboard, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/ChartsLicenseViewController.swift, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/FSLicenseView.storyboard, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseDetailView/FSLicenseViewController.swift, APillLog/APillLog/View/PreferencesTab/Controller/LicenseView/LicenseView.storyboard, APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionViewController.swift, APillLog/APillLog/View/PreferencesTab/Controller/QuestionsView/QuestionsView.storyboard, APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToController.swift, APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToView.storyboard, APillLog/APillLog/View/PreferencesTab/Controller/VersionView/VersionView.storyboard, APillLog/APillLog/View/PreferencesTab/PreferencesView.storyboard, APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift, APillLog/APillLog/View/PreferencesTab/PushNotificationView/PushNotificationView.storyboard
기능, 정보 라벨 타이틀 느낌으로 (ref. medicationView 오늘 복용할 약이에요)
디테일 뷰 들어갔을 때 탭바 숨기기
코코아팟 라이센스 추가
설정 네비게이션 기본 바, 커스텀 바 겹침 현상
=> [Feat] 라이센스 페이지 추가, 텝바 숨기기, 커스텀 바 겹침 해결 

APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillView.storyboard, APillLog/APillLog/View/MedicationTab/AddSecondaryPillView/AddSecondaryPillViewController.swift
- #166 
|이전 화면1|이전화면2|
|---|---|
|수정 후 화면1|수정 후 화면2|
|---|---|
=> [Feat] 추가약 모달 뷰 수정

APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
- 복용률, 증상 빈도 수라는 카테고리 이름 추가
- 복용한 약이 없을 때, 복용한 약이 없어요라는 문구 출력
=> [Feat] History Detail view 수정

APillLog/APillLog/View/PreferencesTab/Controller/ThanksToView/ThanksToView.storyboard
- 카드 Corner Radius 적용
- Scroll View Layout 조정
=> [Fix] ThanksTo View Auto Layout 수정

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/Utility/Calendar/CalendarMonth.swift, APillLog/APillLog/Utility/Calendar/CalendarMonthView.xib, APillLog/APillLog/View/DiaryTab/CustomCellTableViewCell.swift, APillLog/APillLog/View/DiaryTab/DiaryEditViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryReadViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryStorageViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryView.storyboard, APillLog/APillLog/View/DiaryTab/DiaryViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryWriteViewController.swift, APillLog/APillLog/View/DiaryTab/DiaryWriteViewController2.swift, APillLog/APillLog/View/DiaryTab/DiaryWriteViewController3.swift, APillLog/APillLog/View/DiaryTab/MyCustomHeader.swift, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard
1. 동적으로 변화하는 다이어리 테이블 높이
2. 기기 별 크기에 맞게 테이블 높이 조정
3. 과거의 에필로그를 볼 수 있도록 저장소 생성 (달 별로 볼 수 있음)
4. 앱 이름 변경 
5. 이외에도 거슬리는 잡 버그들 수정
https://user-images.githubusercontent.com/72395020/184506525-b58f2b00-4138-487d-90a5-d5506fd6468a.mov
---
https://user-images.githubusercontent.com/72395020/184506585-659ac014-d8ab-4771-889c-52110f270eb0.mp4
close #189 
close #185
=> [Feat] # 189 , # 185 - 다이어리뷰 수정 , 앱 이름 변경

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/CoreData/CoreDataManager.swift, APillLog/APillLog/Extentions/UIView.swift, APillLog/APillLog/View/HistoryTab/HistoryDetail/DIYCalendarCell.swift, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailChartView/HistoryDetailChartView.swift, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift
- fsCalendar
- 시작날짜 클릭 후 종료 날짜 클릭 시 해당 뷰 hidden
- 기간 변경 시 데이터 업데이트
- 복용률이 정렬되지 않음
- 기간이 짧을 때 (2일 등) -> 일 별 빈도가 굵어지는 이슈 존재..
https://user-images.githubusercontent.com/68676844/184423902-fc6f9437-3ea3-4bbe-98fd-c8649a75bc86.mp4
- 캘린더 기간 변경 후 애니메이션 삽입
https://user-images.githubusercontent.com/68676844/184544668-225939a7-1095-4346-8a89-d8ba3ab38d31.mp4
- 선택 막대기가 위로 치우쳐져 있는 문제 해결
=> [Feat] 리포트 뷰 기간 설정 기능 구현

APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
https://user-images.githubusercontent.com/103025266/185840251-a4fbec62-f944-449c-b1e7-5ae5c7e88a30.mp4
rowNumber 가 일치하지 않아서 발생한 버그
reload를 통해 새로운 테이블을 그려서 해결함
=> [Fix] #214 - 추가약 삭제 오류

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/View/MedicationTab/AddPreviousPrimaryPillModal/AddShowPrimaryPillController.swift, APillLog/APillLog/View/MedicationTab/AddPreviousPrimaryPillModal/AddShowPrimaryPillModalView.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/ManageDosingView/ManageDosingViewController.swift, APillLog/APillLog/View/MedicationTab/MedicationView.storyboard, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
- 이전 날짜에서 메인 약 추가 기능 구현
- 메인뷰에서 복용하기 전 수정버튼이 눌렸던 버그 해결
- 전체복용 버튼 오류 수정(버튼상태가 바로 업데이트되지 않았음)
메인 약 추가
https://user-images.githubusercontent.com/103025266/186667367-fdc9c61d-36a5-43a1-8a15-375fd1582c3f.mp4
전체 복용 버튼
https://user-images.githubusercontent.com/103025266/186667461-d3f4910c-bca6-43b4-8110-d28f82a5e7f5.mp4
수정 버튼
-------------------
이전 날짜에 메인약 추가 디자인 피드백 부탁드립니다!
이전 약 기록이라는 워딩을 사용했는데 전반적인 워딩도 검토 부탁드려요!
=> Primary pill/add pill when previous date

APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPill.storyboard, APillLog/APillLog/View/MedicationTab/AddPrimaryPillView/AddPrimaryPillViewController.swift, APillLog/APillLog/View/MedicationTab/MedicationViewController.swift
- 메인 약 직접 추가 구현
- HistoryDetailView 스와이프 제한
|변경 1|변경 2|변경 3|
|---|---|---|
|![Simulator Screen Shot - iPhone 13 - 2022-08-25 at 23 07 59](https://user-images.githubusercontent.com/86882798/186687435-a8e9dcd0-6e88-4b01-9158-dcc58f439eff.png)|![Simulator Screen Shot - iPhone 13 - 2022-08-25 at 22 51 32](https://user-images.githubusercontent.com/86882798/186686962-25a78803-e12f-4cdf-987c-f68597f8901a.png)|![Simulator Screen Shot - iPhone 13 - 2022-08-25 at 23 07 19](https://user-images.githubusercontent.com/86882798/186687131-2ff8148c-509f-4a71-8f26-83006d1e5b2d.png)|
=> [Feat] #217, 186 - 메인 약 직접 추가 및 HistoryDetailView 스와이프 제한

APillLog/APillLog.xcodeproj/project.pbxproj, APillLog/APillLog/Extentions/Apillog+UINavigationController.swift, APillLog/APillLog/View/FSCalendarView/FSCalendarView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailView.storyboard, APillLog/APillLog/View/HistoryTab/HistoryDetail/HistoryDetailViewController.swift, APillLog/APillLog/View/PreferencesTab/PreferencesViewController.swift
- 기존 디테일 리포트 뷰 이슈로 인해 모두 막아 놓았던 스와이프 제스처 구현하였습니다.
https://user-images.githubusercontent.com/68676844/189227619-93f91661-b436-42ab-b29a-8c10ac49c47b.mp4
=> 스와이프 제스처 구현
